/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--brand-background)',
        foreground: 'var(--brand-foreground)',
        card: 'var(--brand-card)',
        'card-foreground': 'var(--brand-card-foreground)',
        muted: 'var(--brand-muted)',
        'muted-foreground': 'var(--brand-muted-foreground)',
        primary: 'var(--brand-primary)',
        'primary-foreground': 'var(--brand-primary-foreground)',
        secondary: 'var(--brand-secondary)',
        'secondary-foreground': 'var(--brand-secondary-foreground)',
        accent: 'var(--brand-accent)',
        'accent-foreground': 'var(--brand-accent-foreground)',
        destructive: 'var(--brand-destructive)',
        'destructive-foreground': 'var(--brand-destructive-foreground)',
        border: 'var(--brand-border)',
        input: 'var(--brand-input)',
        ring: 'var(--brand-ring)',
        cream: '#FDF6EC',
        'cream-dark': '#F5ECD7',
        amber: '#E89B3C',
        'amber-dark': '#D4891F',
        'amber-light': '#F4C67A',
        'brown-dark': '#3D2B1F',
        'brown-light': '#8B6F4E',
        'warm-gray': '#F9F5F0',
        'warm-border': '#E8DFD0',
        'green-diff': '#4A8C5C',
        'green-bg': '#EBF5EE',
        'red-diff': '#C0392B',
        'red-bg': '#FDECEA',
        'code-bg': '#2D2A26',
        'code-text': '#F5E6D3',
        'code-sidebar': '#252320',
      },
      fontFamily: {
        serif: ['Georgia', 'Noto Serif SC', 'serif'],
        sans: ['Inter', 'Noto Sans SC', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      borderRadius: {
        'small': '0.375rem',
        'medium': '0.5rem',
        'large': '0.75rem',
        'xlarge': '1rem',
      },
      boxShadow: {
        'card': '0 2px 12px rgba(61, 43, 31, 0.08)',
        'card-hover': '0 8px 30px rgba(61, 43, 31, 0.14)',
      },
    },
  },
  plugins: [],
}
