const API_BASE = import.meta.env.VITE_API_BASE || '/api/v1'

async function request(endpoint, options = {}) {
  try {
    const response = await fetch(`${API_BASE}${endpoint}`, {
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
      ...options,
    })
    const data = await response.json()
    if (data.code !== 0) {
      throw new Error(data.message || 'Request failed')
    }
    return data.data
  } catch (error) {
    console.warn(`API request failed for ${endpoint}, using fallback:`, error.message)
    return null
  }
}

export const articleAPI = {
  getList: (params = {}) => {
    const query = new URLSearchParams(params).toString()
    return request(`/articles?${query}`)
  },
  getFeatured: (limit = 3) => request(`/articles/featured?limit=${limit}`),
  getById: (id) => request(`/articles/${id}`),
  getBySlug: (slug) => request(`/articles/slug/${slug}`),
  getRelated: (id, category, limit = 4) => 
    request(`/articles/${id}/related?category=${category}&limit=${limit}`),
  like: (id) => request(`/articles/${id}/like`, { method: 'POST' }),
  getCategories: () => request('/articles/categories'),
  getTags: () => request('/articles/tags'),
}

export const adminArticleAPI = {
  getList: (params = {}) => {
    const query = new URLSearchParams(params).toString()
    return request(`/admin/articles?${query}`)
  },
  getStats: () => request('/admin/articles/stats'),
  getDrafts: (limit = 5) => request(`/admin/articles/drafts?limit=${limit}`),
  getCategories: () => request('/admin/articles/categories'),
  getById: (id) => request(`/admin/articles/${id}`),
  create: (data) => request('/admin/articles', {
    method: 'POST',
    body: JSON.stringify(data),
  }),
  update: (id, data) => request(`/admin/articles/${id}`, {
    method: 'PUT',
    body: JSON.stringify(data),
  }),
  delete: (id) => request(`/admin/articles/${id}`, { method: 'DELETE' }),
  batchStatus: (ids, status) => request('/admin/articles/batch/status', {
    method: 'POST',
    body: JSON.stringify({ ids, status }),
  }),
  batchDelete: (ids) => request('/admin/articles/batch/delete', {
    method: 'POST',
    body: JSON.stringify({ ids }),
  }),
}

export const courseAPI = {
  getList: (params = {}) => {
    const query = new URLSearchParams(params).toString()
    return request(`/courses?${query}`)
  },
  getHot: (limit = 4) => request(`/courses/hot?limit=${limit}`),
  getById: (id) => request(`/courses/${id}`),
  getCategories: () => request('/courses/categories'),
}

export const projectAPI = {
  getList: (params = {}) => {
    const query = new URLSearchParams(params).toString()
    return request(`/projects?${query}`)
  },
  getFeatured: (limit = 3) => request(`/projects/featured?limit=${limit}`),
  getById: (id) => request(`/projects/${id}`),
  getLanguages: () => request('/projects/languages'),
}

export const commentAPI = {
  getByArticle: (articleId) => request(`/comments/article/${articleId}`),
  create: (data) => request('/comments', {
    method: 'POST',
    body: JSON.stringify(data),
  }),
}

export const subscriberAPI = {
  subscribe: (email) => request('/subscribers', {
    method: 'POST',
    body: JSON.stringify({ email }),
  }),
}

export const siteAPI = {
  getStats: () => request('/stats'),
  health: () => request('/health'),
}

export const mockData = {
  articles: [
    {
      id: 1,
      title: '理解CAP定理：分布式系统的权衡艺术',
      slug: 'cap-theorem',
      summary: '深入探讨一致性、可用性与分区容错性之间的辩证关系，结合实际案例分析分布式架构设计中的核心决策。',
      content: `## 引言\n\n在分布式系统设计中，CAP定理是一个无法回避的基础理论。它告诉我们，在网络分区不可避免的情况下，一致性（Consistency）和可用性（Availability）无法同时满足。\n\n### CAP的三个维度\n\n- **一致性（Consistency）**：所有节点在同一时间看到相同的数据\n- **可用性（Availability）**：每个请求都能获得非错误的响应\n- **分区容错性（Partition Tolerance）**：系统在网络分区发生时仍能继续运行\n\n> "在分布式系统中，分区是常态，而非异常。" —— 这是理解CAP定理的关键前提。\n\n### CP vs AP：架构的选择\n\n| 选择 | 代表系统 | 适用场景 |\n|------|----------|----------|\n| CP | ZooKeeper, etcd | 配置中心、分布式锁 |\n| AP | Cassandra, DynamoDB | 社交网络、电商推荐 |\n\n### 实践思考\n\n在实际工程中，我们很少看到纯粹的CP或AP系统。更多时候，我们是在**一致性程度**和**可用性延迟**之间做精细的权衡。比如最终一致性、因果一致性等模型，都是这种权衡的产物。\n\n---\n\n理解CAP不是为了背诵定义，而是为了在架构决策时能够清晰地认识到每个选择的代价。`,
      cover: '/assets/image_0_yi19x4.jpg',
      category: '技术',
      tags: 'CAP,分布式',
      read_time: 12,
      word_count: 3200,
      views: 3200,
      likes: 156,
      is_featured: true,
      is_pinned: true,
      allow_comments: true,
      status: 1,
      published_at: '2026-06-28',
      updated_at: '2026-06-28',
      created_at: '2026-06-20',
    },
    {
      id: 2,
      title: 'Kubernetes Operator 模式实战指南',
      slug: 'k8s-operator',
      summary: '从CRD定义到Controller实现，手把手教你构建生产级别的Kubernetes Operator，自动化管理复杂应用。',
      content: `## Operator模式简介\n\nKubernetes Operator是一种封装、部署和管理Kubernetes应用的方法。它通过自定义资源（CRD）和自定义控制器，将运维知识编码到软件中。\n\n### 核心概念\n\n1. **CRD（Custom Resource Definition）**：扩展Kubernetes API，定义自定义资源类型\n2. **Controller**：监听资源变化，执行调谐循环（Reconciliation Loop）\n3. **Reconcile**：将实际状态驱动到期望状态的过程\n\n### 开发步骤\n\n\`\`\`go\nfunc (r *MyAppReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {\n    // 1. 获取自定义资源\n    var myapp appv1.MyApp\n    if err := r.Get(ctx, req.NamespacedName, &myapp); err != nil {\n        return ctrl.Result{}, client.IgnoreNotFound(err)\n    }\n    \n    // 2. 确保Deployment存在\n    // 3. 确保Service存在\n    // 4. 更新状态\n    \n    return ctrl.Result{RequeueAfter: 5 * time.Minute}, nil\n}\n\`\`\`\n\n### 最佳实践\n\n- 使用**Finalizer**处理资源清理\n- 实现**Status Conditions**反映资源状态\n- 设置**Owner References**级联删除\n- 利用**Workqueue**进行事件限流`,
      cover: '/assets/image_1_yi19x4.jpg',
      category: '技术',
      tags: 'Kubernetes,Operator',
      read_time: 18,
      word_count: 4800,
      views: 4893,
      likes: 234,
      is_featured: true,
      is_pinned: false,
      allow_comments: true,
      status: 1,
      published_at: '2026-06-20',
      updated_at: '2026-06-20',
      created_at: '2026-06-10',
    },
    {
      id: 3,
      title: 'Go 并发编程：Goroutine 调度器深度剖析',
      slug: 'go-goroutine-scheduler',
      summary: '追踪Go运行时调度器的GMP模型实现原理，理解工作窃取、抢占式调度等核心机制的内部运作。',
      content: `## GMP模型概述\n\nGo语言的并发性能之所以出色，很大程度上归功于其优秀的运行时调度器。GMP模型是Go调度器的核心设计：\n\n- **G（Goroutine）**：Go协程，包含栈、程序计数器和状态信息\n- **M（Machine）**：操作系统线程，真正执行代码的载体\n- **P（Processor）**：逻辑处理器，持有G的本地队列\n\n### 调度流程\n\n当一个Goroutine被创建时：\n1. 优先放入当前P的本地队列\n2. 如果本地队列满了，放入全局队列\n3. 其他P空闲时会尝试从全局队列或其他P"偷取"G\n\n### 工作窃取（Work Stealing）\n\n> 每个P在完成自己队列中的G后，会随机选择另一个P，从其队列尾部"偷"一半的G。\n\n这种机制保证了负载均衡，避免了某些线程空闲而其他线程过载的情况。\n\n### 系统调用处理\n\n当G进行阻塞系统调用时，M会和P解绑，P会寻找另一个空闲的M继续执行队列中的其他G，确保不浪费CPU资源。`,
      cover: null,
      category: '技术',
      tags: 'Go,并发编程',
      read_time: 15,
      word_count: 4200,
      views: 5621,
      likes: 287,
      is_featured: false,
      is_pinned: false,
      allow_comments: true,
      status: 1,
      published_at: '2026-06-12',
      updated_at: '2026-06-12',
      created_at: '2026-06-05',
    },
    {
      id: 4,
      title: '深入理解分布式系统中的共识算法',
      slug: 'consensus-algorithms',
      summary: '从 Paxos 到 Raft，从拜占庭将军问题到 PBFT，系统性地梳理共识算法的演进脉络，剖析工业界实现（如 etcd/raft）的工程优化细节。',
      content: `## 共识问题的本质\n\n分布式系统中的共识问题，是指如何让多个节点在网络延迟、消息丢失、节点故障的情况下，对某个值或某个操作序列达成一致。\n\n### FLP不可能定理\n\n在异步网络模型中，即使只有一个节点可能故障，也不存在确定性的共识算法能够保证终止。这是我们理解共识算法边界的基础。\n\n### Raft算法\n\nRaft将共识问题分解为三个相对独立的子问题：\n\n1. **Leader选举**：当现有Leader故障时，快速选出新Leader\n2. **日志复制**：Leader接收客户端请求，复制到其他节点\n3. **安全性**：保证任何节点都不会"回退"已经提交的日志\n\n\`\`\`go\n// Raft 节点状态\ntype RaftNode struct {\n    state       NodeState   // Follower, Candidate, Leader\n    currentTerm int\n    votedFor    int\n    log         []LogEntry\n    commitIndex int\n    lastApplied int\n}\n\`\`\`\n\n### 工程优化\n\netcd/raft库在Raft论文基础上做了大量工程优化：\n\n- **流水线复制**：不等待前一个RPC返回就发送下一个\n- **快照机制**：避免日志无限增长\n- **ReadIndex**：提供线性一致读而不必写入日志\n- **Pre-Vote**：防止网络分区恢复后的无效选举`,
      cover: '/assets/image_2_yi19x4.jpg',
      category: '技术',
      tags: '共识算法,Raft,Paxos',
      read_time: 25,
      word_count: 6800,
      views: 8432,
      likes: 421,
      is_featured: true,
      is_pinned: false,
      allow_comments: true,
      status: 1,
      published_at: '2026-06-30',
      updated_at: '2026-06-30',
      created_at: '2026-06-15',
    },
    {
      id: 5,
      title: 'Rust 所有权机制与内存安全',
      slug: 'rust-ownership',
      summary: '深入理解Rust的所有权系统、借用检查器和生命周期，掌握零成本抽象的内存安全编程范式。',
      content: `## 所有权规则\n\nRust的所有权系统是其内存安全的基石，遵循三条核心规则：\n\n1. 每个值都有一个**所有者**\n2. 同一时间只能有**一个**所有者\n3. 当所有者离开作用域，值被**丢弃**\n\n### 移动语义\n\n\`\`\`rust\nlet s1 = String::from("hello");\nlet s2 = s1; // s1的所有权移动到s2\n// println!("{}", s1); // 编译错误！s1不再有效\n\`\`\`\n\n### 借用与引用\n\n- **不可变引用**（&T）：可以同时有多个\n- **可变引用**（&mut T）：同一时间只能有一个\n- 引用必须**总是有效**\n\n### 生命周期\n\n生命周期标注告诉编译器引用之间的有效范围关系：\n\n\`\`\`rust\nfn longest<'a>(x: &'a str, y: &'a str) -> &'a str {\n    if x.len() > y.len() { x } else { y }\n}\n\`\`\`\n\n> 生命周期的本质是**避免悬垂引用**，让编译器在编译期就能发现内存安全问题。`,
      cover: '/assets/image_4_yi19x4.jpg',
      category: '技术',
      tags: 'Rust,内存安全',
      read_time: 14,
      word_count: 3800,
      views: 2100,
      likes: 165,
      is_featured: false,
      is_pinned: false,
      allow_comments: true,
      status: 1,
      published_at: '2026-06-08',
      updated_at: '2026-06-08',
      created_at: '2026-06-01',
    },
    {
      id: 6,
      title: 'Docker 多阶段构建最佳实践',
      slug: 'docker-multistage-build',
      summary: '通过多阶段构建优化Docker镜像大小，结合Go、React等实际项目场景演示生产级Dockerfile编写技巧。',
      content: `## 为什么需要多阶段构建\n\n传统Dockerfile构建的镜像往往包含编译工具、源码、依赖等大量运行时不需要的文件，导致镜像体积庞大，存在安全隐患。\n\n### Go项目示例\n\n\`\`\`dockerfile\n# 构建阶段\nFROM golang:1.21-alpine AS builder\nWORKDIR /app\nCOPY go.mod go.sum ./\nRUN go mod download\nCOPY . .\nRUN CGO_ENABLED=0 GOOS=linux go build -o myapp ./cmd/server\n\n# 运行阶段\nFROM alpine:3.18\nRUN apk --no-cache add ca-certificates tzdata\nWORKDIR /root/\nCOPY --from=builder /app/myapp .\nEXPOSE 8080\nCMD ["./myapp"]\n\`\`\`\n\n### React项目示例\n\n\`\`\`dockerfile\n# 构建阶段\nFROM node:18-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\n\n# 运行阶段\nFROM nginx:alpine\nCOPY --from=builder /app/dist /usr/share/nginx/html\nCOPY nginx.conf /etc/nginx/conf.d/default.conf\nEXPOSE 80\n\`\`\`\n\n### 关键技巧\n\n- 使用\`--from=builder\`只复制构建产物\n- 选择尽可能小的基础镜像（alpine/distroless/scratch）\n- 利用层缓存优化构建速度`,
      cover: null,
      category: '技术',
      tags: 'Docker,DevOps',
      read_time: 10,
      word_count: 2600,
      views: 1800,
      likes: 98,
      is_featured: false,
      is_pinned: false,
      allow_comments: true,
      status: 1,
      published_at: '2026-06-05',
      updated_at: '2026-06-05',
      created_at: '2026-05-28',
    },
    {
      id: 7,
      title: 'TypeScript 5.0 装饰器与类型体操',
      slug: 'typescript-decorators',
      summary: '详解TypeScript 5.0新特性，包括装饰器标准化、const类型参数以及高级类型编程技巧。',
      content: `## TypeScript 5.0 新特性\n\nTypeScript 5.0带来了多项重要更新，其中最引人注目的是装饰器的标准化支持。\n\n### 装饰器基础\n\n\`\`\`typescript\nfunction logged(target: any, context: ClassMethodDecoratorContext) {\n    const methodName = String(context.name);\n    return function (this: any, ...args: any[]) {\n        console.log(\`Calling \${methodName}\`);\n        return target.apply(this, args);\n    };\n}\n\nclass Calculator {\n    @logged\n    add(a: number, b: number) {\n        return a + b;\n    }\n}\n\`\`\`\n\n### const类型参数\n\n\`\`\`typescript\n// TypeScript 5.0 前\nfunction getNames<T extends readonly string[]>(arr: T): T[number][] {\n    return arr;\n}\n\n// TypeScript 5.0 后\nconst getNamesConst = <const T extends readonly string[]>(arr: T) => arr;\nconst names = getNamesConst(["Alice", "Bob"] as const);\n// typeof names: readonly ["Alice", "Bob"]\n\`\`\``,
      cover: null,
      category: '技术',
      tags: 'TypeScript,前端',
      read_time: 8,
      word_count: 2100,
      views: 1500,
      likes: 87,
      is_featured: false,
      is_pinned: false,
      allow_comments: true,
      status: 1,
      published_at: '2026-06-01',
      updated_at: '2026-06-01',
      created_at: '2026-05-25',
    },
    {
      id: 8,
      title: '从零搭建CI/CD流水线（草稿）',
      slug: 'cicd-pipeline-draft',
      summary: '基于GitHub Actions和ArgoCD构建完整的持续集成与持续部署流程。',
      content: `## CI/CD概述\n\n持续集成和持续部署是现代软件开发的基础实践。\n\n### 流水线设计\n\n- **代码检查**：Lint、类型检查\n- **单元测试**：自动化测试\n- **构建镜像**：Docker镜像构建\n- **安全扫描**：漏洞检测\n- **部署发布**：自动/手动审批`,
      cover: null,
      category: '教程',
      tags: 'CI/CD,GitHub Actions',
      read_time: 20,
      word_count: 800,
      views: 0,
      likes: 0,
      is_featured: false,
      is_pinned: false,
      allow_comments: true,
      status: 0,
      published_at: null,
      updated_at: '2026-06-25',
      created_at: '2026-06-25',
    },
    {
      id: 9,
      title: '微服务链路追踪入门（草稿）',
      slug: 'tracing-intro-draft',
      summary: 'OpenTelemetry与Jaeger实践，构建分布式系统可观测性体系。',
      content: `## 可观测性三支柱\n\n- **Metrics**：指标聚合\n- **Logging**：事件日志\n- **Tracing**：请求链路\n\n### OpenTelemetry\n\nOpenTelemetry是云原生计算基金会下的可观测性标准项目，统一了追踪和指标的API与SDK。`,
      cover: null,
      category: '技术',
      tags: '链路追踪,OpenTelemetry',
      read_time: 16,
      word_count: 1200,
      views: 0,
      likes: 0,
      is_featured: false,
      is_pinned: false,
      allow_comments: true,
      status: 0,
      published_at: null,
      updated_at: '2026-06-22',
      created_at: '2026-06-22',
    },
  ],
  adminStats: {
    total_articles: 9,
    published: 7,
    draft: 2,
    archived: 0,
    monthly_views: 27526,
  },
  courses: [
    {
      id: 1,
      title: '分布式系统实战：从理论到生产',
      description: '系统性学习分布式系统核心概念，从基础理论到工业级实践，涵盖共识算法、服务发现、负载均衡等核心主题。',
      cover: '/assets/image_1_yi19x4.jpg',
      category: '分布式系统',
      level: '进阶',
      duration: '42小时',
      lessons_count: 86,
      students_count: 2356,
      rating: 4.9,
      price: 299,
      is_free: false,
      is_hot: true,
    },
    {
      id: 2,
      title: 'Go 语言工程实践入门',
      description: '从零开始学习Go语言，掌握语法特性、并发编程、工程规范，具备独立开发Go项目的能力。',
      cover: '/assets/image_2_yi19x4.jpg',
      category: 'Go语言',
      level: '入门',
      duration: '28小时',
      lessons_count: 64,
      students_count: 3421,
      rating: 4.8,
      price: 0,
      is_free: true,
      is_hot: true,
    },
    {
      id: 3,
      title: 'Kubernetes 云原生部署实战',
      description: '深入理解Kubernetes架构，掌握容器编排、服务网格、可观测性等云原生核心技术栈。',
      cover: '/assets/image_3_yi19x4.jpg',
      category: '云原生',
      level: '进阶',
      duration: '36小时',
      lessons_count: 72,
      students_count: 1892,
      rating: 4.7,
      price: 199,
      is_free: false,
      is_hot: false,
    },
    {
      id: 4,
      title: 'React 全栈开发实战',
      description: '从组件设计到状态管理，从前端工程化到全栈API开发，构建现代化Web应用。',
      cover: '/assets/image_4_yi19x4.jpg',
      category: '前端工程',
      level: '入门',
      duration: '32小时',
      lessons_count: 58,
      students_count: 4210,
      rating: 4.9,
      price: 0,
      is_free: true,
      is_hot: true,
    },
  ],
  projects: [
    {
      id: 1,
      name: 'GoDist',
      slug: 'godist',
      description: '轻量级 Go 微服务框架，内置服务发现、负载均衡与熔断降级能力。',
      logo: null,
      cover: '/assets/image_0_yi19x4.jpg',
      github_url: 'https://github.com/codewalker/godist',
      demo_url: null,
      docs_url: 'https://godist.codewalker.dev',
      tags: 'Go,gRPC,Raft,etcd',
      language: 'Go',
      stars: 2300,
      forks: 342,
      is_featured: true,
    },
    {
      id: 2,
      name: 'KubeView',
      slug: 'kubeview',
      description: 'Kubernetes 集群可视化管理工具，提供直观的资源拓扑视图与监控告警。',
      logo: null,
      cover: '/assets/image_1_yi19x4.jpg',
      github_url: 'https://github.com/codewalker/kubeview',
      demo_url: 'https://demo.kubeview.dev',
      docs_url: 'https://kubeview.codewalker.dev',
      tags: 'Kubernetes,React,TypeScript',
      language: 'TypeScript',
      stars: 1800,
      forks: 256,
      is_featured: true,
    },
    {
      id: 3,
      name: 'FlowEngine',
      slug: 'flowengine',
      description: '轻量级分布式工作流引擎，支持DAG编排、任务调度与重试补偿机制。',
      logo: null,
      cover: null,
      github_url: 'https://github.com/codewalker/flowengine',
      demo_url: null,
      docs_url: null,
      tags: 'Go,工作流,DAG',
      language: 'Go',
      stars: 890,
      forks: 123,
      is_featured: true,
    },
    {
      id: 4,
      name: 'CacheBench',
      slug: 'cachebench',
      description: '多缓存组件性能压测工具，支持Redis、Memcached、本地缓存对比测试。',
      logo: null,
      cover: null,
      github_url: 'https://github.com/codewalker/cachebench',
      demo_url: null,
      docs_url: null,
      tags: 'Go,缓存,Benchmark',
      language: 'Go',
      stars: 456,
      forks: 67,
      is_featured: false,
    },
    {
      id: 5,
      name: 'LogCollector',
      slug: 'logcollector',
      description: '基于eBPF的高性能日志采集Agent，低资源占用，支持多种输出。',
      logo: null,
      cover: null,
      github_url: 'https://github.com/codewalker/logcollector',
      demo_url: null,
      docs_url: null,
      tags: 'Rust,eBPF,可观测性',
      language: 'Rust',
      stars: 678,
      forks: 89,
      is_featured: false,
    },
    {
      id: 6,
      name: 'APITestKit',
      slug: 'apitestkit',
      description: 'API自动化测试框架，支持契约测试、压力测试与回归测试，集成CI/CD。',
      logo: null,
      cover: null,
      github_url: 'https://github.com/codewalker/apitestkit',
      demo_url: null,
      docs_url: null,
      tags: 'Go,API测试,CI/CD',
      language: 'Go',
      stars: 345,
      forks: 45,
      is_featured: false,
    },
  ],
  stats: {
    article_count: 42,
    course_count: 12,
    project_count: 18,
    student_count: 5000,
    subscriber_count: 3200,
  },
  categories: ['技术', '随笔', '教程', '生活', 'AI', '其他'],
  tags: [
    { name: 'Go', count: 23 },
    { name: 'Kubernetes', count: 18 },
    { name: '并发编程', count: 15 },
    { name: '微服务', count: 14 },
    { name: 'React', count: 12 },
    { name: '分布式', count: 11 },
    { name: 'Docker', count: 10 },
    { name: '性能优化', count: 9 },
    { name: 'Rust', count: 8 },
    { name: 'gRPC', count: 7 },
  ],
}
