const API_BASE = import.meta.env.VITE_API_BASE || '/api/v1'

async function request(endpoint, options = {}) {
  try {
    const response = await fetch(`${API_BASE}${endpoint}`, {
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
      ...options,
    })
    const data = await response.json()
    if (data.code !== 0) {
      throw new Error(data.message || 'Request failed')
    }
    return data.data
  } catch (error) {
    console.warn(`API request failed for ${endpoint}, using fallback:`, error.message)
    return null
  }
}

export const articleAPI = {
  getList: (params = {}) => {
    const query = new URLSearchParams(params).toString()
    return request(`/articles?${query}`)
  },
  getFeatured: (limit = 3) => request(`/articles/featured?limit=${limit}`),
  getById: (id) => request(`/articles/${id}`),
  getBySlug: (slug) => request(`/articles/slug/${slug}`),
  getRelated: (id, category, limit = 4) => 
    request(`/articles/${id}/related?category=${category}&limit=${limit}`),
  like: (id) => request(`/articles/${id}/like`, { method: 'POST' }),
  getCategories: () => request('/articles/categories'),
  getTags: () => request('/articles/tags'),
}

export const courseAPI = {
  getList: (params = {}) => {
    const query = new URLSearchParams(params).toString()
    return request(`/courses?${query}`)
  },
  getHot: (limit = 4) => request(`/courses/hot?limit=${limit}`),
  getById: (id) => request(`/courses/${id}`),
  getCategories: () => request('/courses/categories'),
}

export const projectAPI = {
  getList: (params = {}) => {
    const query = new URLSearchParams(params).toString()
    return request(`/projects?${query}`)
  },
  getFeatured: (limit = 3) => request(`/projects/featured?limit=${limit}`),
  getById: (id) => request(`/projects/${id}`),
  getLanguages: () => request('/projects/languages'),
}

export const commentAPI = {
  getByArticle: (articleId) => request(`/comments/article/${articleId}`),
  create: (data) => request('/comments', {
    method: 'POST',
    body: JSON.stringify(data),
  }),
}

export const subscriberAPI = {
  subscribe: (email) => request('/subscribers', {
    method: 'POST',
    body: JSON.stringify({ email }),
  }),
}

export const siteAPI = {
  getStats: () => request('/stats'),
  health: () => request('/health'),
}

export const mockData = {
  articles: [
    {
      id: 1,
      title: '理解CAP定理：分布式系统的权衡艺术',
      slug: 'cap-theorem',
      summary: '深入探讨一致性、可用性与分区容错性之间的辩证关系，结合实际案例分析分布式架构设计中的核心决策。',
      cover: '/assets/image_0_yi19x4.jpg',
      category: '分布式系统',
      tags: 'CAP,分布式',
      read_time: 12,
      views: 3200,
      likes: 156,
      is_featured: true,
      published_at: '2026-06-28',
    },
    {
      id: 2,
      title: 'Kubernetes Operator 模式实战指南',
      slug: 'k8s-operator',
      summary: '从CRD定义到Controller实现，手把手教你构建生产级别的Kubernetes Operator，自动化管理复杂应用。',
      cover: '/assets/image_1_yi19x4.jpg',
      category: '云原生',
      tags: 'Kubernetes,Operator',
      read_time: 18,
      views: 4893,
      likes: 234,
      is_featured: true,
      published_at: '2026-06-20',
    },
    {
      id: 3,
      title: 'Go 并发编程：Goroutine 调度器深度剖析',
      slug: 'go-goroutine-scheduler',
      summary: '追踪Go运行时调度器的GMP模型实现原理，理解工作窃取、抢占式调度等核心机制的内部运作。',
      cover: null,
      category: 'Go语言',
      tags: 'Go,并发编程',
      read_time: 15,
      views: 5621,
      likes: 287,
      is_featured: false,
      published_at: '2026-06-12',
    },
    {
      id: 4,
      title: '深入理解分布式系统中的共识算法',
      slug: 'consensus-algorithms',
      summary: '从 Paxos 到 Raft，从拜占庭将军问题到 PBFT，系统性地梳理共识算法的演进脉络，剖析工业界实现（如 etcd/raft）的工程优化细节。',
      cover: '/assets/image_2_yi19x4.jpg',
      category: '分布式系统',
      tags: '共识算法,Raft,Paxos',
      read_time: 25,
      views: 8432,
      likes: 421,
      is_featured: true,
      published_at: '2026-06-30',
    },
    {
      id: 5,
      title: 'Raft 共识算法工程实现指南',
      slug: 'raft-implementation',
      summary: '从 Leader 选举到日志复制，详解 etcd/raft 库的核心实现与生产环境踩坑经验。',
      cover: null,
      category: '分布式系统',
      tags: 'Raft,共识算法',
      read_time: 18,
      views: 5621,
      likes: 234,
      is_featured: false,
      published_at: '2026-06-25',
    },
    {
      id: 6,
      title: 'React 19 新特性全景解读',
      slug: 'react-19-features',
      summary: 'Server Components、Actions、useOptimistic 等新特性的实战应用与性能分析。',
      cover: '/assets/image_3_yi19x4.jpg',
      category: '前端工程',
      tags: 'React,前端',
      read_time: 15,
      views: 7234,
      likes: 345,
      is_featured: false,
      published_at: '2026-06-15',
    },
    {
      id: 7,
      title: '从零构建 Go 微服务框架',
      slug: 'go-microservice-framework',
      summary: '服务发现、负载均衡、熔断降级，一个轻量级框架的设计思考与代码实现。',
      cover: '/assets/image_4_yi19x4.jpg',
      category: '开源实践',
      tags: 'Go,微服务',
      read_time: 28,
      views: 9156,
      likes: 567,
      is_featured: false,
      published_at: '2026-06-10',
    },
    {
      id: 8,
      title: '高并发系统的缓存设计艺术',
      slug: 'cache-design',
      summary: '缓存穿透、击穿、雪崩的解决方案，多级缓存架构与一致性保证策略。',
      cover: null,
      category: '架构设计',
      tags: '缓存,高并发',
      read_time: 20,
      views: 6547,
      likes: 312,
      is_featured: false,
      published_at: '2026-06-05',
    },
    {
      id: 9,
      title: 'Go 内存管理与 GC 调优实战',
      slug: 'go-gc-tuning',
      summary: 'TCMalloc 思想、三色标记清除、逃逸分析，以及如何写出 GC 友好的代码。',
      cover: '/assets/image_0_yi19x4.jpg',
      category: 'Go语言',
      tags: 'Go,GC,性能优化',
      read_time: 24,
      views: 5892,
      likes: 278,
      is_featured: false,
      published_at: '2026-05-30',
    },
  ],
  courses: [
    {
      id: 1,
      title: '分布式系统实战：从理论到生产',
      description: '系统性学习分布式系统核心概念，从基础理论到工业级实践，涵盖共识算法、服务发现、负载均衡等核心主题。',
      cover: '/assets/image_1_yi19x4.jpg',
      category: '分布式系统',
      level: '进阶',
      duration: '42小时',
      lessons_count: 86,
      students_count: 2356,
      rating: 4.9,
      price: 299,
      is_free: false,
      is_hot: true,
    },
    {
      id: 2,
      title: 'Go 语言工程实践入门',
      description: '从零开始学习Go语言，掌握语法特性、并发编程、工程规范，具备独立开发Go项目的能力。',
      cover: '/assets/image_2_yi19x4.jpg',
      category: 'Go语言',
      level: '入门',
      duration: '28小时',
      lessons_count: 64,
      students_count: 3421,
      rating: 4.8,
      price: 0,
      is_free: true,
      is_hot: true,
    },
    {
      id: 3,
      title: 'Kubernetes 云原生部署实战',
      description: '深入理解Kubernetes架构，掌握容器编排、服务网格、可观测性等云原生核心技术栈。',
      cover: '/assets/image_3_yi19x4.jpg',
      category: '云原生',
      level: '进阶',
      duration: '36小时',
      lessons_count: 72,
      students_count: 1892,
      rating: 4.7,
      price: 199,
      is_free: false,
      is_hot: false,
    },
    {
      id: 4,
      title: 'React 全栈开发实战',
      description: '从组件设计到状态管理，从前端工程化到全栈API开发，构建现代化Web应用。',
      cover: '/assets/image_4_yi19x4.jpg',
      category: '前端工程',
      level: '入门',
      duration: '32小时',
      lessons_count: 58,
      students_count: 4210,
      rating: 4.9,
      price: 0,
      is_free: true,
      is_hot: true,
    },
  ],
  projects: [
    {
      id: 1,
      name: 'GoDist',
      slug: 'godist',
      description: '轻量级 Go 微服务框架，内置服务发现、负载均衡与熔断降级能力。',
      logo: null,
      cover: '/assets/image_0_yi19x4.jpg',
      github_url: 'https://github.com/codewalker/godist',
      demo_url: null,
      docs_url: 'https://godist.codewalker.dev',
      tags: 'Go,gRPC,Raft,etcd',
      language: 'Go',
      stars: 2300,
      forks: 342,
      is_featured: true,
    },
    {
      id: 2,
      name: 'KubeView',
      slug: 'kubeview',
      description: 'Kubernetes 集群可视化管理工具，提供直观的资源拓扑视图与监控告警。',
      logo: null,
      cover: '/assets/image_1_yi19x4.jpg',
      github_url: 'https://github.com/codewalker/kubeview',
      demo_url: 'https://demo.kubeview.dev',
      docs_url: 'https://kubeview.codewalker.dev',
      tags: 'Kubernetes,React,TypeScript',
      language: 'TypeScript',
      stars: 1800,
      forks: 256,
      is_featured: true,
    },
    {
      id: 3,
      name: 'FlowEngine',
      slug: 'flowengine',
      description: '轻量级分布式工作流引擎，支持DAG编排、任务调度与重试补偿机制。',
      logo: null,
      cover: null,
      github_url: 'https://github.com/codewalker/flowengine',
      demo_url: null,
      docs_url: null,
      tags: 'Go,工作流,DAG',
      language: 'Go',
      stars: 890,
      forks: 123,
      is_featured: true,
    },
    {
      id: 4,
      name: 'CacheBench',
      slug: 'cachebench',
      description: '多缓存组件性能压测工具，支持Redis、Memcached、本地缓存对比测试。',
      logo: null,
      cover: null,
      github_url: 'https://github.com/codewalker/cachebench',
      demo_url: null,
      docs_url: null,
      tags: 'Go,缓存,Benchmark',
      language: 'Go',
      stars: 456,
      forks: 67,
      is_featured: false,
    },
    {
      id: 5,
      name: 'LogCollector',
      slug: 'logcollector',
      description: '基于eBPF的高性能日志采集Agent，低资源占用，支持多种输出。',
      logo: null,
      cover: null,
      github_url: 'https://github.com/codewalker/logcollector',
      demo_url: null,
      docs_url: null,
      tags: 'Rust,eBPF,可观测性',
      language: 'Rust',
      stars: 678,
      forks: 89,
      is_featured: false,
    },
    {
      id: 6,
      name: 'APITestKit',
      slug: 'apitestkit',
      description: 'API自动化测试框架，支持契约测试、压力测试与回归测试，集成CI/CD。',
      logo: null,
      cover: null,
      github_url: 'https://github.com/codewalker/apitestkit',
      demo_url: null,
      docs_url: null,
      tags: 'Go,API测试,CI/CD',
      language: 'Go',
      stars: 345,
      forks: 45,
      is_featured: false,
    },
  ],
  stats: {
    article_count: 42,
    course_count: 12,
    project_count: 18,
    student_count: 5000,
    subscriber_count: 3200,
  },
  categories: ['分布式系统', '前端工程', 'Go语言', '开源实践', '云原生', '架构设计'],
  tags: [
    { name: 'Go', count: 23 },
    { name: 'Kubernetes', count: 18 },
    { name: '并发编程', count: 15 },
    { name: '微服务', count: 14 },
    { name: 'React', count: 12 },
    { name: '分布式', count: 11 },
    { name: 'Docker', count: 10 },
    { name: '性能优化', count: 9 },
    { name: 'Rust', count: 8 },
    { name: 'gRPC', count: 7 },
  ],
}
